[local]
localhost

[mongodb]
mongodb-dev.nemani.online

[catalogue]
catalogue-dev.nemani.online

[redis]
redis-dev.nemani.online

[user]
user-dev.nemani.online

[cart]
cart-dev.nemani.online

[mysql]
mysql-dev.nemani.online

[shipping]
shipping-dev.nemani.online

[payment]
payment-dev.nemani.online

[rabbitmq]
rabbitmq-dev.nemani.online

[frontend]
frontend-dev.nemani.online